### PR TITLE
Return true if func

### PR DESCRIPTION
**Pull request by chinedufn**
assert-function implies that you are asserting whether `arg` is a function

### CODE REVIEW

**Comment by bendrucker** [comment]
Nope, sometimes throw sometimes return true is unnecessary. You use asserts to break execution flow, not for type checks.

**Comment by chinedufn** [comment]
Hmm indeed :o

**Comment by bendrucker** [comment]
not in my house

**Comment by chinedufn** [comment]
I'm lol omg

**Pull request closed without merging**
